#!/usr/bin/env node
// Added shebang

const request = require("request");
// importing "request" module

const URL = process.argv[2];
// const of URL. Since node runs as "node filename -arg", [2] is the correct index

console.log('Checking response for', URL);
// logging for debugging purpose, to see if const actually worked

if( ! URL || 0 === URL.length) {
  console.log('URL is empty'); 
    return;
  }
if( ! URL.toLowerCase().includes('https')) {
  console.log('URL is accepted in HTTPS only');
} else {
  request(
    { method: 'GET'
    , uri: URL
    , gzip: true
    }
  , function (error, response, body) {
      console.log('Body response: ' + body)
    }
  )
    .on('response', function(response) {
      console.log('Status Code:', response.statusCode)
      console.log(response.headers)
  });
}

/*

*/