#!/usr/bin/env node
// Added shebang

import request from 'request';
// importing "request" module

const URL = process.argv[2];
// const of URL. Since node runs as "node filename -arg", [2] is the correct index

console.log('Checking response for', URL);
// logging for debugging purpose, to see if const actually worked

if( ! URL || 0 === URL.length) {
  console.log('URL is empty'); 
    return;
  }
if( ! URL.toLowerCase().includes('https')) {
  console.log('URL is accepted in HTTPS only');
} else {
  request(URL, function(response, body) {
    console.log('statusCode:', response && response.statusCode);
    console.log(body);
  });
}

/*
First IF line checks to see if URL is passed as empty, then handles error.

Second IF line is checking to see if the argument includes https, otherwise givin errors.

If it passes the https string check, then it'll run REQUEST library to grab the response.
Within resonse, it'll also print status code for the https call.

*/