#!/usr/bin/env node

const request = require("request");

const URL = process.argv[2];
const username = process.argv[3];

const password = process.argv[4];

console.log('Running POST to', URL);

if( ! URL || 0 === URL.length) {
  console.log('URL is empty'); 
    return;
  }
if( ! URL.toLowerCase().includes('https')) {
  console.log('URL is accepted in HTTPS only');
} else {
  request.post(URL).auth(username, password, true)
  .on('response', function(response) {
    console.log('Status Code:', response.statusCode)
    console.log(response.headers)
    })
  }

/*

*/